  - name: installation of apache2 and php packages on Ubuntu
    tags: apache2,ubuntu,php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: installation of apache and php packages on Centos
    tags: apache2,centos,php
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Amazon"

  - name: started httpd (Centos)
    tags: apache2,centos,php
    service:
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution == "Amazon"

  - name: Copying of default.html to web server
    tags: html,copy
    copy:
      src: default-site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  - name: Changing Email in httpd
    tags: apache2,centos,php
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin khan@testing.com
    when: ansible_distribution == "Amazon"
    register: httpd

  - name: Restart httpd (Centos)
    tags: apache2,centos,php
    service:
      name: httpd
      state: restarted
    when: httpd.changed

